### model
#model_name_or_path: {{Qwen2.5-7B-Instruct Path}}
model_name_or_path: /workspace/asr/huggingface.cache/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28 

### method
stage: sft
do_train: true
finetuning_type: full
#deepspeed: {{examples/deepspeed/ds_z3_config.json from llama-factory}}
deepspeed: /workspace/asr/finr1/dianjinr1/LLaMA-Factory/examples/deepspeed/ds_z3_config.json 

### dataset
#dataset: cflue_oe_r1,cflue_mcq_r1,fin_qa_r1,ccc_r1
dataset: dianjinr1_data 
dataset_dir: /workspace/asr/finr1/dianjinr1/dianjinr1-data
template: qwen
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: experiments/checkpoints/Qwen2.5-7B-Instruct-R1
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
#num_train_epochs: 3.0
num_train_epochs: 10.0
lr_scheduler_type: linear
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
